// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "icoffee",
            "email": "1596740959@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analysis/class_avg": {
            "get": {
                "description": "获取每个班级的平均成绩，用于图表展示",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "获取班级平均成绩",
                "responses": {
                    "200": {
                        "description": "班级平均成绩数组",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ClassAvgDoc"
                            }
                        }
                    },
                    "500": {
                        "description": "数据库查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analysis/exam_count": {
            "get": {
                "description": "按 course_id 和 exam_date 去重统计考试次数（即课程+考试日视为一次考试）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "获取考试总次数",
                "responses": {
                    "200": {
                        "description": "格式: { \\\"total\\\": 23 }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analysis/monthly": {
            "get": {
                "description": "获取每月平均成绩的时间序列数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "获取月度平均成绩趋势",
                "responses": {
                    "200": {
                        "description": "月度平均成绩列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Result"
                            }
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analysis/pass_rate": {
            "get": {
                "description": "可选传入 course_id 获取单个课程，否则返回所有课程通过率",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "获取课程通过率分析",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1001,
                        "description": "课程 ID（可选，单个课程）",
                        "name": "course_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通过率列表或单个课程分析",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Pass"
                            }
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analysis/rank": {
            "get": {
                "description": "获取学生按平均成绩排名的前10名",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "获取成绩排行榜（含姓名）",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 0,
                        "description": "起始位置（默认0）",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "description": "返回数量（默认10）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "学生平均成绩排行榜",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ScoreRankRow"
                            }
                        }
                    },
                    "500": {
                        "description": "数据库查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analysis/rank/cache": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "清空成绩排行榜缓存",
                "responses": {
                    "200": {
                        "description": "清除结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "清除失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analytics/course-stats": {
            "get": {
                "description": "获取每门课程的平均、最高和最低成绩",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "获取课程统计",
                "responses": {
                    "200": {
                        "description": "课程统计列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CourseStats"
                            }
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/classes": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "获取班级列表",
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "添加班级",
                "parameters": [
                    {
                        "description": "班级信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Class"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/classes/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "更新班级",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "班级ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "班级信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Class"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classes"
                ],
                "summary": "删除班级",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "班级ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/permissions": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permission"
                ],
                "summary": "获取权限列表",
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permission"
                ],
                "summary": "添加权限",
                "parameters": [
                    {
                        "description": "权限信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/permissions/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permission"
                ],
                "summary": "删除权限",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "权限ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/role/permission_ids": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "获取角色的权限ID列表",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 2,
                        "description": "角色ID",
                        "name": "role_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/role/permissions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permission"
                ],
                "summary": "设置角色权限",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/roles": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "获取角色列表",
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "添加角色",
                "parameters": [
                    {
                        "description": "角色信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/roles/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/scores": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scores"
                ],
                "summary": "获取成绩列表",
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scores"
                ],
                "summary": "添加成绩",
                "parameters": [
                    {
                        "description": "成绩信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Score"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/scores/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scores"
                ],
                "summary": "更新成绩",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "成绩ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "成绩信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Score"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scores"
                ],
                "summary": "删除成绩",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "成绩ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/students": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "获取学生列表",
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "添加学生",
                "parameters": [
                    {
                        "description": "学生信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Student"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/students/by_class": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "根据班级获取学生",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"软件一班\"",
                        "description": "班级名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/students/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "更新学生信息",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "学生ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "学生信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Student"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "删除学生",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "学生ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/user/permissions": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取当前用户权限",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/user/role": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_role"
                ],
                "summary": "获取用户角色 ID",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_role"
                ],
                "summary": "设置用户角色",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/user/roles": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取当前用户角色",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "添加用户",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/users/{id}/reset_password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "重置用户密码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "用户登录，获取 JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回 token 信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/charts": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "图表列表",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"score-trend\"",
                        "description": "图表类型（可选）",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "新增图表",
                "parameters": [
                    {
                        "description": "图表数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChartData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/charts/data": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "获取图表数据",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"score-trend\"",
                        "description": "图表类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图表数据内容",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "缺少参数",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "删除图表数据",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"pass-rate\"",
                        "description": "图表类型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数缺失",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/charts/types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "图表类型列表",
                "responses": {
                    "200": {
                        "description": "图表类型集合",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/charts/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "更新图表",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"60f7d2f5e13f1e3c48a2a1a2\"",
                        "description": "图表ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "图表数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChartData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "删除图表",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"60f7d2f5e13f1e3c48a2a1a2\"",
                        "description": "图表ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/dashboard/stats": {
            "get": {
                "description": "包括学生数、课程数、班级数、平均成绩",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "仪表盘统计数据",
                "responses": {
                    "200": {
                        "description": "统计数据",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/doc/models": {
            "get": {
                "description": "此接口无实际用途，仅用于强制 Swagger 输出所有模型结构体定义",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelDocs"
                ],
                "summary": "[文档] 展示所有模型结构体（用于 Swagger 展示）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.docModels"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.docModels": {
            "type": "object",
            "properties": {
                "chart_data": {
                    "$ref": "#/definitions/models.ChartData"
                },
                "class": {
                    "$ref": "#/definitions/models.ClassDoc"
                },
                "class_avg": {
                    "$ref": "#/definitions/models.ClassAvgDoc"
                },
                "course": {
                    "$ref": "#/definitions/models.CourseDoc"
                },
                "course_stats": {
                    "$ref": "#/definitions/models.CourseStats"
                },
                "login_request": {
                    "$ref": "#/definitions/models.LoginRequest"
                },
                "pass": {
                    "$ref": "#/definitions/models.Pass"
                },
                "permission": {
                    "$ref": "#/definitions/models.Permission"
                },
                "permission_doc": {
                    "$ref": "#/definitions/models.PermissionDoc"
                },
                "result": {
                    "$ref": "#/definitions/models.Result"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                },
                "role_doc": {
                    "$ref": "#/definitions/models.RoleDoc"
                },
                "role_permission": {
                    "$ref": "#/definitions/models.RolePermission"
                },
                "score": {
                    "$ref": "#/definitions/models.ScoreDoc"
                },
                "score_rank": {
                    "$ref": "#/definitions/models.ScoreRankRow"
                },
                "student": {
                    "$ref": "#/definitions/models.StudentDoc"
                },
                "user": {
                    "$ref": "#/definitions/models.UserDoc"
                },
                "user_role": {
                    "$ref": "#/definitions/models.UserRole"
                }
            }
        },
        "models.ChartData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "string",
                    "example": "monthly"
                },
                "values": {}
            }
        },
        "models.Class": {
            "type": "object"
        },
        "models.ClassAvgDoc": {
            "type": "object",
            "properties": {
                "avg_score": {
                    "type": "number",
                    "example": 85.2
                },
                "class_name": {
                    "type": "string",
                    "example": "高一1班"
                }
            }
        },
        "models.ClassDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "高一1班"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        },
        "models.CourseDoc": {
            "type": "object",
            "properties": {
                "course_code": {
                    "type": "string",
                    "example": "MATH101"
                },
                "course_name": {
                    "type": "string",
                    "example": "数学"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "credit": {
                    "type": "number",
                    "example": 3
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "teacher_id": {
                    "type": "integer",
                    "example": 10
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        },
        "models.CourseStats": {
            "type": "object",
            "properties": {
                "avg_score": {
                    "type": "number",
                    "example": 85.3
                },
                "course_id": {
                    "type": "integer",
                    "example": 101
                },
                "max_score": {
                    "type": "number",
                    "example": 98
                },
                "min_score": {
                    "type": "number",
                    "example": 62
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.Pass": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "integer",
                    "example": 101
                },
                "passed": {
                    "type": "integer",
                    "example": 45
                },
                "rate": {
                    "type": "number",
                    "example": 90
                },
                "total": {
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "models.Permission": {
            "description": "权限定义，例如 \"student:view\"",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1716940800
                },
                "description": {
                    "description": "权限说明",
                    "type": "string",
                    "example": "查看学生列表"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "权限标识",
                    "type": "string",
                    "example": "student:view"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1716940800
                }
            }
        },
        "models.PermissionDoc": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "key": {
                    "type": "string",
                    "example": "student:view"
                },
                "name": {
                    "type": "string",
                    "example": "学生管理"
                }
            }
        },
        "models.Result": {
            "type": "object",
            "properties": {
                "avg": {
                    "type": "number",
                    "example": 82.7
                },
                "month": {
                    "type": "string",
                    "example": "2024-06"
                }
            }
        },
        "models.Role": {
            "description": "角色定义，例如 \"admin\"",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer",
                    "example": 1716940800
                },
                "description": {
                    "description": "角色说明",
                    "type": "string",
                    "example": "系统管理员"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "角色标识",
                    "type": "string",
                    "example": "admin"
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1716940800
                }
            }
        },
        "models.RoleDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "管理员"
                }
            }
        },
        "models.RolePermission": {
            "description": "角色与权限的绑定关系",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "permission_id": {
                    "type": "integer",
                    "example": 2
                },
                "role_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Score": {
            "type": "object"
        },
        "models.ScoreDoc": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "integer",
                    "example": 101
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "exam_date": {
                    "type": "string",
                    "example": "2025-05-01"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "score": {
                    "type": "number",
                    "example": 89.5
                },
                "student_id": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        },
        "models.ScoreRankRow": {
            "type": "object",
            "properties": {
                "avg_score": {
                    "type": "number",
                    "example": 87.5
                },
                "student_name": {
                    "type": "string",
                    "example": "张三"
                }
            }
        },
        "models.Student": {
            "type": "object"
        },
        "models.StudentDoc": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "2005-09-01"
                },
                "class_id": {
                    "type": "integer",
                    "example": 2
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "gender": {
                    "type": "string",
                    "example": "男"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "张三"
                },
                "student_no": {
                    "type": "string",
                    "example": "20230001"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        },
        "models.UserDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "nickname": {
                    "type": "string",
                    "example": "管理员"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.UserRole": {
            "description": "用户与角色的绑定关系",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "role_id": {
                    "type": "integer",
                    "example": 1
                },
                "user_id": {
                    "type": "integer",
                    "example": 3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.1",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "学生成绩管理系统 API",
	Description:      "用于管理学生、课程、成绩和图表数据的后台 API。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
